### PR TITLE
Assignment 1 Done

### PR DESCRIPTION
**Pull request by hirish99**

### CODE REVIEW

**Comment by adrian-szwejk** [comment]
Nice job on FizzBuzz, I liked your variation on the logic and structure of the app. If you'd like to get ahead, I'd recommend reading through the slides from last year for meeting 4/5 and starting the next weekly assignment.

**Comment by hirish99** [comment]
Okay man. I might make it better though and add more features like in the video.

**Comment by adrian-szwejk** [comment]
Yeah, sounds good. The other features aren't too hard to implement if you've setup the functions and button properly for the first part so I'll look forward to seeing your updated pull request with that addition.

**Comment by hirish99** [comment]
Assignent 2 Done

**Pull request closed without merging**
